import {MigrationInterface, QueryRunner} from "typeorm";

export class TableDefinition1553382484087 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "tds"."role" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "value" character varying NOT NULL, CONSTRAINT "UQ_e0ec7232270d164c5ab4210a13f" UNIQUE ("value"), CONSTRAINT "PK_db8397a4b1293eec017c6a5c757" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."account" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "ID" character varying NOT NULL, "code" integer, "token" character varying, "status" text NOT NULL DEFAULT 'ACTIVE', "roleId" uuid NOT NULL, CONSTRAINT "PK_caf48f6fb2d3f06fe7b00554148" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."city" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, CONSTRAINT "UQ_b5ce1d1f964c97c77965f28fa68" UNIQUE ("name"), CONSTRAINT "PK_fcbb70e3aa0b9fa0ffefd95deb8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."ngo_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "code" SERIAL NOT NULL, CONSTRAINT "UQ_909a0b7030ca288f8729b207e89" UNIQUE ("name"), CONSTRAINT "PK_3294cd43c250fb8a1f34f9a4b73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."trading_point_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, CONSTRAINT "UQ_8aedab6701278ef800490164a5e" UNIQUE ("name"), CONSTRAINT "PK_25eeb422c64515a27a32a273a03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."period" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "from" TIMESTAMP NOT NULL, "to" TIMESTAMP NOT NULL, "interval" integer NOT NULL, "type" character varying NOT NULL, "relationId" uuid, CONSTRAINT "REL_d094957c5d90f44a5b26a21ff4" UNIQUE ("relationId"), CONSTRAINT "PK_2078fb5af1eec209fe59ca32d0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."partner_payment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "ID" character varying NOT NULL, "paymentNumber" character varying, "isPaid" boolean NOT NULL DEFAULT false, "price" numeric, "partnerPaymentAt" TIMESTAMP, "tradingPointId" uuid, "periodId" uuid, CONSTRAINT "PK_d1a3b9d7236a7af4f8607bcba2e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."phone_prefix" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "value" integer NOT NULL, "code" character varying NOT NULL, "maxLength" integer NOT NULL, CONSTRAINT "UQ_a9a417f39acfdaa70798508cb7d" UNIQUE ("value"), CONSTRAINT "PK_36dbe128012c75ca4f2239b80cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."phone" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "value" integer NOT NULL, "prefixId" uuid, CONSTRAINT "UQ_1bfae5568210688a61ef1735615" UNIQUE ("value"), CONSTRAINT "UQ_1bfae5568210688a61ef1735615" UNIQUE ("value"), CONSTRAINT "PK_a8d8348ba9b757831b644376ce6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."correction" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "price" integer NOT NULL, "transactionPrice" integer NOT NULL, "transactionPool" integer NOT NULL, "pool" integer NOT NULL, "status" character varying NOT NULL, "isVerified" boolean NOT NULL, "terminalId" uuid, "tradingPointId" uuid, "transactionId" uuid, "userId" uuid, CONSTRAINT "REL_527a58898a5f6f67552bbad7c6" UNIQUE ("transactionId"), CONSTRAINT "PK_ae5d4e42506b5688746defc2da6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."terminal" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "step" text, "ID" character varying NOT NULL, "isMain" boolean NOT NULL DEFAULT false, "name" character varying, "phoneId" uuid, "tradingPointId" uuid, "accountId" uuid, CONSTRAINT "REL_fffa38b90e45cb71d458ac4c36" UNIQUE ("accountId"), CONSTRAINT "PK_b517cc4dc31a52b41ad96713833" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."trading_point" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "ID" character varying NOT NULL, "name" character varying NOT NULL, "donationPercentage" numeric NOT NULL, "vat" numeric NOT NULL, "fee" numeric NOT NULL, "image" character varying, "xp" integer NOT NULL, "active" boolean NOT NULL DEFAULT false, "closedAt" TIMESTAMP, "typeId" uuid, "phoneId" uuid, "addressId" uuid, CONSTRAINT "UQ_b9b01d988aedccece4706890df9" UNIQUE ("name"), CONSTRAINT "PK_f28493fededb1bcebe3abed2875" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."transaction" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "ID" character varying NOT NULL, "price" numeric NOT NULL, "donationPercentage" numeric NOT NULL, "provisionPercentage" numeric NOT NULL, "paymentValue" numeric NOT NULL, "vat" numeric NOT NULL, "provision" numeric NOT NULL, "poolValue" numeric NOT NULL, "userXp" integer NOT NULL, "tradingPointXp" integer NOT NULL, "isCorrection" boolean NOT NULL, "class" character varying NOT NULL DEFAULT 'TRANSACTION', "tradingPointId" uuid, "userId" uuid, "terminalId" uuid, "paymentId" uuid, "donationId" uuid, CONSTRAINT "PK_baee4fc73dbbb6168138ca40e8b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."user_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "xp" integer NOT NULL DEFAULT 0, "name" character varying, "email" character varying, "lastName" character varying, "bankAccount" integer, "collectedMoney" numeric NOT NULL DEFAULT 0, "ngoTempMoney" numeric NOT NULL DEFAULT 0, "ngoSelectionCount" integer NOT NULL DEFAULT 0, "ngoId" uuid, CONSTRAINT "PK_f035c89d623b6b1d2e777eee549" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."virtual_card" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "ID" character varying NOT NULL, "code" uuid NOT NULL DEFAULT uuid_generate_v4(), "donationPool" numeric NOT NULL DEFAULT 0, "personalPool" numeric NOT NULL DEFAULT 0, CONSTRAINT "PK_a16f5c2c316ce652ef14e664b0d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."opinion" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "value" character varying NOT NULL, "email" character varying NOT NULL, "userId" uuid, CONSTRAINT "PK_4e3bc119daadf99d395159aeeb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "transactionId" character varying NOT NULL, "message" character varying NOT NULL, "userId" uuid, CONSTRAINT "PK_da855be6cd80d059a4baf8f2b9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."user_payout" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "accountNumber" character varying NOT NULL, "price" integer NOT NULL, "class" character varying NOT NULL DEFAULT 'PAYOUT', "userId" uuid, CONSTRAINT "PK_dd9a82d44a98871558510fef5d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "registered" boolean NOT NULL DEFAULT false, "isAnonymous" boolean NOT NULL DEFAULT false, "detailsId" uuid, "cardId" uuid, "phoneId" uuid, "accountId" uuid, CONSTRAINT "REL_42ddc5d1ddbe9087e5af084148" UNIQUE ("cardId"), CONSTRAINT "REL_04193ccd288aa2f6be17bd6ee0" UNIQUE ("accountId"), CONSTRAINT "PK_4e8f28d38026a467c075730674e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."donation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "ID" character varying NOT NULL, "invoiceNumber" character varying, "type" text NOT NULL, "pool" text NOT NULL, "price" numeric NOT NULL, "isPaid" boolean NOT NULL DEFAULT false, "payedAt" TIMESTAMP, "ngoId" uuid, "userId" uuid, "periodId" uuid, CONSTRAINT "PK_228d950dccac8c23f879be433eb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."physical_card" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "ID" character varying NOT NULL, "code" uuid NOT NULL DEFAULT uuid_generate_v4(), "collectedMoney" numeric NOT NULL DEFAULT 0, CONSTRAINT "PK_ad686116b29da9e212dc1be4120" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."ngo" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "ID" character varying NOT NULL, "bankNumber" character varying NOT NULL, "email" character varying NOT NULL, "verified" boolean NOT NULL, "verifiedAt" TIMESTAMP, "name" character varying NOT NULL, "longName" character varying NOT NULL, "description" character varying(550) NOT NULL, "image" character varying, "thumbnail" character varying, "isTadeus" boolean NOT NULL, "totalDonation" integer, "lastDonation" integer, "phoneId" uuid, "cardId" uuid, "addressId" uuid, "typeId" uuid, CONSTRAINT "UQ_50e91dcc7d952a43ddb4b9163a6" UNIQUE ("name"), CONSTRAINT "REL_91a7cd89e4c301fb7bec619b3b" UNIQUE ("cardId"), CONSTRAINT "PK_236c91786e36351fb31a46e3c76" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."address" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "street" character varying NOT NULL, "number" integer NOT NULL, "postCode" character varying NOT NULL, "longitude" numeric NOT NULL, "latitude" numeric NOT NULL, "distance" numeric NOT NULL, "coordinate" geometry(Point,4326), "cityId" uuid, CONSTRAINT "PK_e050cfe0f98249c62da842d08f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."admin" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "phoneId" uuid, "accountId" uuid, CONSTRAINT "REL_04532b3facc74abdb611841d49" UNIQUE ("accountId"), CONSTRAINT "PK_072f1c322a6064825926d39619b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds"."configuration" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "minNgoTransfer" numeric NOT NULL, "minPersonalPool" numeric NOT NULL, "userExpirationAfterDays" integer NOT NULL, "type" character varying NOT NULL, CONSTRAINT "PK_04229e1535f1bf6f3b299300373" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "tds"."account" ADD CONSTRAINT "FK_b284b05807b2d5690d7ee34015d" FOREIGN KEY ("roleId") REFERENCES "tds"."role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."period" ADD CONSTRAINT "FK_d094957c5d90f44a5b26a21ff42" FOREIGN KEY ("relationId") REFERENCES "tds"."period"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."partner_payment" ADD CONSTRAINT "FK_0a122d032e107aa19f03c8e4a7f" FOREIGN KEY ("tradingPointId") REFERENCES "tds"."trading_point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."partner_payment" ADD CONSTRAINT "FK_6c5d13ec91c26e5d6578d8245bd" FOREIGN KEY ("periodId") REFERENCES "tds"."period"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."phone" ADD CONSTRAINT "FK_b9b6196ed8fe593d7904e7bf670" FOREIGN KEY ("prefixId") REFERENCES "tds"."phone_prefix"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."correction" ADD CONSTRAINT "FK_7332758b54cb2b1a1ba770385a0" FOREIGN KEY ("terminalId") REFERENCES "tds"."terminal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."correction" ADD CONSTRAINT "FK_12442bb02e7f1218f07fcfba6e7" FOREIGN KEY ("tradingPointId") REFERENCES "tds"."trading_point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."correction" ADD CONSTRAINT "FK_527a58898a5f6f67552bbad7c6f" FOREIGN KEY ("transactionId") REFERENCES "tds"."transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."correction" ADD CONSTRAINT "FK_27036d8c70d556183412feec4ea" FOREIGN KEY ("userId") REFERENCES "tds"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."terminal" ADD CONSTRAINT "FK_e79f0b7ea9ecbf4b8f40d24253c" FOREIGN KEY ("phoneId") REFERENCES "tds"."phone"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."terminal" ADD CONSTRAINT "FK_7ba07c350062802f4948b469f86" FOREIGN KEY ("tradingPointId") REFERENCES "tds"."trading_point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."terminal" ADD CONSTRAINT "FK_fffa38b90e45cb71d458ac4c36f" FOREIGN KEY ("accountId") REFERENCES "tds"."account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."trading_point" ADD CONSTRAINT "FK_d5e5b865ed5296d09901b891c69" FOREIGN KEY ("typeId") REFERENCES "tds"."trading_point_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."trading_point" ADD CONSTRAINT "FK_4be822e01c714d6894d90deb9db" FOREIGN KEY ("phoneId") REFERENCES "tds"."phone"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."trading_point" ADD CONSTRAINT "FK_1d751751e68adb3257823b990ad" FOREIGN KEY ("addressId") REFERENCES "tds"."address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."transaction" ADD CONSTRAINT "FK_148fbc69dfa97f23673afaee1cb" FOREIGN KEY ("tradingPointId") REFERENCES "tds"."trading_point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."transaction" ADD CONSTRAINT "FK_6361d5c5109a6ec878d7061a49f" FOREIGN KEY ("userId") REFERENCES "tds"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."transaction" ADD CONSTRAINT "FK_e654db8c17a162786878b778e45" FOREIGN KEY ("terminalId") REFERENCES "tds"."terminal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."transaction" ADD CONSTRAINT "FK_9d3a6339d255f6ad4521b33f400" FOREIGN KEY ("paymentId") REFERENCES "tds"."partner_payment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."transaction" ADD CONSTRAINT "FK_db295f5979743cef102e7508ac3" FOREIGN KEY ("donationId") REFERENCES "tds"."donation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."user_details" ADD CONSTRAINT "FK_6c546ad433ac7b1d0150d56a4a0" FOREIGN KEY ("ngoId") REFERENCES "tds"."ngo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."opinion" ADD CONSTRAINT "FK_c2bc20b7e827fc68371d0796aed" FOREIGN KEY ("userId") REFERENCES "tds"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."notification" ADD CONSTRAINT "FK_27af2ee7a4191d01d59230237a2" FOREIGN KEY ("userId") REFERENCES "tds"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."user_payout" ADD CONSTRAINT "FK_5d32aba8500e6b273bcfe78e867" FOREIGN KEY ("userId") REFERENCES "tds"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."user" ADD CONSTRAINT "FK_7e02d86b39f8d14a6d3a6edcb6d" FOREIGN KEY ("detailsId") REFERENCES "tds"."user_details"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."user" ADD CONSTRAINT "FK_42ddc5d1ddbe9087e5af0841483" FOREIGN KEY ("cardId") REFERENCES "tds"."virtual_card"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."user" ADD CONSTRAINT "FK_9d4eab4c58d829d575301f57f7c" FOREIGN KEY ("phoneId") REFERENCES "tds"."phone"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."user" ADD CONSTRAINT "FK_04193ccd288aa2f6be17bd6ee0e" FOREIGN KEY ("accountId") REFERENCES "tds"."account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."donation" ADD CONSTRAINT "FK_f7a32e3c9838b53aed8d8d6ca6c" FOREIGN KEY ("ngoId") REFERENCES "tds"."ngo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."donation" ADD CONSTRAINT "FK_4371365fb9333b231d98695a88c" FOREIGN KEY ("userId") REFERENCES "tds"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."donation" ADD CONSTRAINT "FK_c0401f2ac4e6fb718c1cacc72d6" FOREIGN KEY ("periodId") REFERENCES "tds"."period"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."ngo" ADD CONSTRAINT "FK_91bcda4eaca210f4e8a2e57d9b7" FOREIGN KEY ("phoneId") REFERENCES "tds"."phone"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."ngo" ADD CONSTRAINT "FK_91a7cd89e4c301fb7bec619b3be" FOREIGN KEY ("cardId") REFERENCES "tds"."physical_card"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."ngo" ADD CONSTRAINT "FK_860ff8ecc471309564dbd7e6e58" FOREIGN KEY ("addressId") REFERENCES "tds"."address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."ngo" ADD CONSTRAINT "FK_6cc2194f4792921e70f36226481" FOREIGN KEY ("typeId") REFERENCES "tds"."ngo_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."address" ADD CONSTRAINT "FK_783cce88249b382920ebd422038" FOREIGN KEY ("cityId") REFERENCES "tds"."city"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."admin" ADD CONSTRAINT "FK_c647a1bae3c15d96eee211fa9c3" FOREIGN KEY ("phoneId") REFERENCES "tds"."phone"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tds"."admin" ADD CONSTRAINT "FK_04532b3facc74abdb611841d499" FOREIGN KEY ("accountId") REFERENCES "tds"."account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "tds"."admin" DROP CONSTRAINT "FK_04532b3facc74abdb611841d499"`);
        await queryRunner.query(`ALTER TABLE "tds"."admin" DROP CONSTRAINT "FK_c647a1bae3c15d96eee211fa9c3"`);
        await queryRunner.query(`ALTER TABLE "tds"."address" DROP CONSTRAINT "FK_783cce88249b382920ebd422038"`);
        await queryRunner.query(`ALTER TABLE "tds"."ngo" DROP CONSTRAINT "FK_6cc2194f4792921e70f36226481"`);
        await queryRunner.query(`ALTER TABLE "tds"."ngo" DROP CONSTRAINT "FK_860ff8ecc471309564dbd7e6e58"`);
        await queryRunner.query(`ALTER TABLE "tds"."ngo" DROP CONSTRAINT "FK_91a7cd89e4c301fb7bec619b3be"`);
        await queryRunner.query(`ALTER TABLE "tds"."ngo" DROP CONSTRAINT "FK_91bcda4eaca210f4e8a2e57d9b7"`);
        await queryRunner.query(`ALTER TABLE "tds"."donation" DROP CONSTRAINT "FK_c0401f2ac4e6fb718c1cacc72d6"`);
        await queryRunner.query(`ALTER TABLE "tds"."donation" DROP CONSTRAINT "FK_4371365fb9333b231d98695a88c"`);
        await queryRunner.query(`ALTER TABLE "tds"."donation" DROP CONSTRAINT "FK_f7a32e3c9838b53aed8d8d6ca6c"`);
        await queryRunner.query(`ALTER TABLE "tds"."user" DROP CONSTRAINT "FK_04193ccd288aa2f6be17bd6ee0e"`);
        await queryRunner.query(`ALTER TABLE "tds"."user" DROP CONSTRAINT "FK_9d4eab4c58d829d575301f57f7c"`);
        await queryRunner.query(`ALTER TABLE "tds"."user" DROP CONSTRAINT "FK_42ddc5d1ddbe9087e5af0841483"`);
        await queryRunner.query(`ALTER TABLE "tds"."user" DROP CONSTRAINT "FK_7e02d86b39f8d14a6d3a6edcb6d"`);
        await queryRunner.query(`ALTER TABLE "tds"."user_payout" DROP CONSTRAINT "FK_5d32aba8500e6b273bcfe78e867"`);
        await queryRunner.query(`ALTER TABLE "tds"."notification" DROP CONSTRAINT "FK_27af2ee7a4191d01d59230237a2"`);
        await queryRunner.query(`ALTER TABLE "tds"."opinion" DROP CONSTRAINT "FK_c2bc20b7e827fc68371d0796aed"`);
        await queryRunner.query(`ALTER TABLE "tds"."user_details" DROP CONSTRAINT "FK_6c546ad433ac7b1d0150d56a4a0"`);
        await queryRunner.query(`ALTER TABLE "tds"."transaction" DROP CONSTRAINT "FK_db295f5979743cef102e7508ac3"`);
        await queryRunner.query(`ALTER TABLE "tds"."transaction" DROP CONSTRAINT "FK_9d3a6339d255f6ad4521b33f400"`);
        await queryRunner.query(`ALTER TABLE "tds"."transaction" DROP CONSTRAINT "FK_e654db8c17a162786878b778e45"`);
        await queryRunner.query(`ALTER TABLE "tds"."transaction" DROP CONSTRAINT "FK_6361d5c5109a6ec878d7061a49f"`);
        await queryRunner.query(`ALTER TABLE "tds"."transaction" DROP CONSTRAINT "FK_148fbc69dfa97f23673afaee1cb"`);
        await queryRunner.query(`ALTER TABLE "tds"."trading_point" DROP CONSTRAINT "FK_1d751751e68adb3257823b990ad"`);
        await queryRunner.query(`ALTER TABLE "tds"."trading_point" DROP CONSTRAINT "FK_4be822e01c714d6894d90deb9db"`);
        await queryRunner.query(`ALTER TABLE "tds"."trading_point" DROP CONSTRAINT "FK_d5e5b865ed5296d09901b891c69"`);
        await queryRunner.query(`ALTER TABLE "tds"."terminal" DROP CONSTRAINT "FK_fffa38b90e45cb71d458ac4c36f"`);
        await queryRunner.query(`ALTER TABLE "tds"."terminal" DROP CONSTRAINT "FK_7ba07c350062802f4948b469f86"`);
        await queryRunner.query(`ALTER TABLE "tds"."terminal" DROP CONSTRAINT "FK_e79f0b7ea9ecbf4b8f40d24253c"`);
        await queryRunner.query(`ALTER TABLE "tds"."correction" DROP CONSTRAINT "FK_27036d8c70d556183412feec4ea"`);
        await queryRunner.query(`ALTER TABLE "tds"."correction" DROP CONSTRAINT "FK_527a58898a5f6f67552bbad7c6f"`);
        await queryRunner.query(`ALTER TABLE "tds"."correction" DROP CONSTRAINT "FK_12442bb02e7f1218f07fcfba6e7"`);
        await queryRunner.query(`ALTER TABLE "tds"."correction" DROP CONSTRAINT "FK_7332758b54cb2b1a1ba770385a0"`);
        await queryRunner.query(`ALTER TABLE "tds"."phone" DROP CONSTRAINT "FK_b9b6196ed8fe593d7904e7bf670"`);
        await queryRunner.query(`ALTER TABLE "tds"."partner_payment" DROP CONSTRAINT "FK_6c5d13ec91c26e5d6578d8245bd"`);
        await queryRunner.query(`ALTER TABLE "tds"."partner_payment" DROP CONSTRAINT "FK_0a122d032e107aa19f03c8e4a7f"`);
        await queryRunner.query(`ALTER TABLE "tds"."period" DROP CONSTRAINT "FK_d094957c5d90f44a5b26a21ff42"`);
        await queryRunner.query(`ALTER TABLE "tds"."account" DROP CONSTRAINT "FK_b284b05807b2d5690d7ee34015d"`);
        await queryRunner.query(`DROP TABLE "tds"."configuration"`);
        await queryRunner.query(`DROP TABLE "tds"."admin"`);
        await queryRunner.query(`DROP TABLE "tds"."address"`);
        await queryRunner.query(`DROP TABLE "tds"."ngo"`);
        await queryRunner.query(`DROP TABLE "tds"."physical_card"`);
        await queryRunner.query(`DROP TABLE "tds"."donation"`);
        await queryRunner.query(`DROP TABLE "tds"."user"`);
        await queryRunner.query(`DROP TABLE "tds"."user_payout"`);
        await queryRunner.query(`DROP TABLE "tds"."notification"`);
        await queryRunner.query(`DROP TABLE "tds"."opinion"`);
        await queryRunner.query(`DROP TABLE "tds"."virtual_card"`);
        await queryRunner.query(`DROP TABLE "tds"."user_details"`);
        await queryRunner.query(`DROP TABLE "tds"."transaction"`);
        await queryRunner.query(`DROP TABLE "tds"."trading_point"`);
        await queryRunner.query(`DROP TABLE "tds"."terminal"`);
        await queryRunner.query(`DROP TABLE "tds"."correction"`);
        await queryRunner.query(`DROP TABLE "tds"."phone"`);
        await queryRunner.query(`DROP TABLE "tds"."phone_prefix"`);
        await queryRunner.query(`DROP TABLE "tds"."partner_payment"`);
        await queryRunner.query(`DROP TABLE "tds"."period"`);
        await queryRunner.query(`DROP TABLE "tds"."trading_point_type"`);
        await queryRunner.query(`DROP TABLE "tds"."ngo_type"`);
        await queryRunner.query(`DROP TABLE "tds"."city"`);
        await queryRunner.query(`DROP TABLE "tds"."account"`);
        await queryRunner.query(`DROP TABLE "tds"."role"`);
    }

}
